[package]
name = "sim_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3"
rand = "0.8"

[features]
training = []

[[bin]]
name = "neat_train"
path = "src/main.rs"
