# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/neural_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/neural_service.proto\x12\x06neural\"6\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x12\n\nmodel_type\x18\x02 \x01(\t\"J\n\x0fPredictResponse\x12\x15\n\rprobabilities\x18\x01 \x03(\x02\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x11\n\tbest_move\x18\x03 \x01(\x05\"P\n\x13\x42\x61tchPredictRequest\x12%\n\x06inputs\x18\x01 \x03(\x0b\x32\x15.neural.InputFeatures\x12\x12\n\nmodel_type\x18\x02 \x01(\t\"!\n\rInputFeatures\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"@\n\x14\x42\x61tchPredictResponse\x12(\n\x07outputs\x18\x01 \x03(\x0b\x32\x17.neural.PredictResponse\"&\n\x10ModelInfoRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\"t\n\x11ModelInfoResponse\x12\x12\n\ninput_size\x18\x01 \x01(\x05\x12\x13\n\x0bhidden_size\x18\x02 \x01(\x05\x12\x13\n\x0boutput_size\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x11\n\tframework\x18\x05 \x01(\t2\xe1\x01\n\rNeuralService\x12<\n\x07Predict\x12\x16.neural.PredictRequest\x1a\x17.neural.PredictResponse\"\x00\x12K\n\x0c\x42\x61tchPredict\x12\x1b.neural.BatchPredictRequest\x1a\x1c.neural.BatchPredictResponse\"\x00\x12\x45\n\x0cGetModelInfo\x12\x18.neural.ModelInfoRequest\x1a\x19.neural.ModelInfoResponse\"\x00\x42\x31Z/github.com/zachbeta/neural_rps/pkg/neural/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.neural_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/zachbeta/neural_rps/pkg/neural/proto'
  _globals['_PREDICTREQUEST']._serialized_start=38
  _globals['_PREDICTREQUEST']._serialized_end=92
  _globals['_PREDICTRESPONSE']._serialized_start=94
  _globals['_PREDICTRESPONSE']._serialized_end=168
  _globals['_BATCHPREDICTREQUEST']._serialized_start=170
  _globals['_BATCHPREDICTREQUEST']._serialized_end=250
  _globals['_INPUTFEATURES']._serialized_start=252
  _globals['_INPUTFEATURES']._serialized_end=285
  _globals['_BATCHPREDICTRESPONSE']._serialized_start=287
  _globals['_BATCHPREDICTRESPONSE']._serialized_end=351
  _globals['_MODELINFOREQUEST']._serialized_start=353
  _globals['_MODELINFOREQUEST']._serialized_end=391
  _globals['_MODELINFORESPONSE']._serialized_start=393
  _globals['_MODELINFORESPONSE']._serialized_end=509
  _globals['_NEURALSERVICE']._serialized_start=512
  _globals['_NEURALSERVICE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
